version: '3.8'
services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: ['server', '/data', '--console-address', ':9001']
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminpass
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio_data:/data
    restart: unless-stopped
  mc:
    container_name: mc
    image: minio/mc
    depends_on:
      - minio
    environment:
      MINIO_ROOT_USER: "admin"
      MINIO_ROOT_PASSWORD: "adminpass"
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://minio:9000 admin adminpass;
      mc mb myminio/sample;
      mc cp init_data/* myminio/sample;
      "
    volumes:
      - ./init_data:/init_data
