name: exec

on:
  workflow_dispatch:
  push:
    tags: [v-*]

jobs:
  exec:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Create .env file
        run: echo $'${{ secrets.DOTENV }}' > .env
      - name: Run docker daemon
        run: docker-compose up -d
      - name: Install dependencies
        run: yarn install
      - name: Run script
        run: yarn start
